coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto 

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
