# Build and serve the documentation locally, with live updates, by using this file:
# ```shell
# julia --project=. -e 'include("docs/liveserver.jl")'
# ```

const LS_PATH_ROOT = dirname(@__DIR__)
const LS_PATH_DOCS = joinpath(LS_PATH_ROOT, "docs")

# Make sure `docs` environment is set up properly.
import Pkg
Pkg.resolve()
Pkg.instantiate()
Pkg.activate(@__DIR__)
Pkg.resolve()
Pkg.instantiate()

# Communicate with `make.jl` that we are running in live mode, so that we can load `Revise` there.
push!(ARGS, "running_local_liveserver")

# Serve documentation now.
import LiveServer
LiveServer.servedocs(;
    include_dirs=[
        joinpath(LS_PATH_ROOT, "src"),           # watch `src/` for changes (to update docstrings)
    ],
    include_files=[
        joinpath(LS_PATH_DOCS, "generate.jl"),   # watch `generate.jl` for changes (to regenerate docs)
        joinpath(LS_PATH_DOCS, "changelog.jl"),  # watch `changelog.jl` for changes (to regenerate changelog)
        joinpath(LS_PATH_ROOT, "CHANGELOG.md"),  # watch `CHANGELOG.md` for changes (to regenerate changelog)
    ],
    skip_files=[
        joinpath(LS_PATH_DOCS, "src", "pages", "changelog.md"),  # don't watch this, because it's generated by `generate.jl` 
    ],
    launch_browser=true,
    verbose=true,
)
